Ledger ctrl
Chivapchichi2/Smart_finance_app_be pull request #6
Opened 2021-10-05 19:18 UTC by f957-cua

merge 'ledger/ctrl to dev'

2021-10-05 19:58 UTC, Chivapchichi2 requested changes
просмотри

2021-10-05 19:58 UTC, Chivapchichi2 commented on middleware/authenticate.js
> +const UserDB = require('../repositories/auth');
зачем?

2021-10-05 19:58 UTC, Chivapchichi2 commented on middleware/authenticate.js
> +      throw new Unauthorized('Not authorized');
"Not authorized"  и так по умолчанию

2021-10-05 20:13 UTC, f957-cua commented on middleware/authenticate.js
> +      throw new Unauthorized('Not authorized');
хотел оставить текстом и потом разделить на две ошибки для удобства пользователей:
Unauthorized передаст код ошибки, а мы можем написать текст для неправильного пароля, или логина
но сейчас этот текст лишний

2021-10-05 20:14 UTC, f957-cua commented on middleware/authenticate.js
> +const UserDB = require('../repositories/auth');
потому что эту мидлвару мы будем тестировать
я вынес обращение к базе в репозиторий

2021-10-06 06:57 UTC, Chivapchichi2 commented on middleware/authenticate.js
> +const UserDB = require('../repositories/auth');
ок

2021-10-06 06:57 UTC, Chivapchichi2 commented on middleware/authenticate.js
> +      throw new Unauthorized('Not authorized');
ок

2021-10-06 06:58 UTC, Chivapchichi2 approved these changes

2021-10-06 06:58 UTC, merged